### ISSUE TITLE
Automate the whole migration process

### ISSUE THREAD

**Issue by robert-zaremba** [cosmos/qa-integration#13]
Dependencies:
- two binaries: app v1, app v2.

The script should easily do the following:
- setup a network of app @ v1
- prepare and execute the upgrade for app @ v2 

Flow
- create a network with node app v1
- creating a software upgrade proposal
- copy new version to relevant nodes
- perform upgrade

**Comment by kaustubhkapatral** [comment]
@robert-zaremba The script does not need to add the upgrade handler to app v2 if it is not present right? Just build the new binary and place it in the right directories?

**Comment by anilCSE** [comment]
closed via #36
