### ISSUE TITLE
Improve the structure of the load tests

### ISSUE THREAD

**Issue by robert-zaremba** [cosmos/qa-integration#3]
### Context

In the first round we implemented simple node / network provisioning (using only the localhost) and few scripts to do query and tx tests. They are mixed together and we don't do checks.

### Objectives

- [x] Create 2 directories: `provision` and  `load_tests` and organize files in the repositories.
- [x] Clean up print lines / echos and only print if there is an error
- [ ] #8 Tracked in https://github.com/cosmos/qa-integration/pull/12
- [ ] #9
- [ ] When something is wrong, stop the loops.
- [ ] #10
- [ ] #11 Tracked in https://github.com/cosmos/qa-integration/pull/14

**Comment by robert-zaremba** [comment]
We can optimize the code look&feel / size a bit. Eg: https://stackoverflow.com/a/12691027/297094

**Comment by anilCSE** [comment]
#35 addressed this refactoring.
